title: Drawin
description: >-
  Digital Art Club that gives out monthly prompts that members will interpret through their illustrations.
baseurl: ''
url: "https://drawin-club.neocities.org"

# Build settings
source: public

collections:
  posts:
    permalink: /post/:categories/:year-:title:output_ext